### ISSUE TITLE
Bug - Komma is geen juiste invoer bij optie "voldoende grens"

### ISSUE THREAD

**Issue by ituir** [HarryDeKat/Silvio#5]
**Beschrijf de fout**
er zit geen komma op het toetsenbord waar je de voldoende grens kan invullen. Ook kan je je ingevoerde waarde nergens opslaan zover ik weet

**Fout reproduceren**
Stappen om het gedrag te reproduceren:
1. Ga naar 'instellingen'
2. Klik op 'voldoende grens'
3. Opslaan werkt niet, kommagetal werkt niet?

**Verwacht gedrag**
dat er een komma is en dat de app de ingevoerde waarde kan opslaan

**Schermafbeeldingen**
Voeg indien van toepassing schermafbeeldingen toe van de fout
![IMG_0203](https://github.com/HarryDeKat/Silvio/assets/79328695/8babe49e-572d-490d-bf02-530bc57620af)

**Smartphone (gelieve de volgende gegevens in te vullen):**
  - Toestel: iPhone 8
  - Besturingssysteem: iOS 16.5
  - Versie: 1.1.00005

**Aanvullende context**
Voeg hier een andere context over het probleem toe.

**Comment by HarryDeKat** [comment]
Whoops, dat ben ik inderdaad vergeten, maar als het goed is werken punten op het moment wel. Het opslaan werkt alleen als je op enter klikt, maar ik kan mij voorstellen dat dit wat onduidelijk is, dus mocht ik binnenkort tijd hebben zal ik het aanpassen.

**Comment by ituir** [comment]
Beide werken niet 🙈Op 27 jun. 2023 om 13:10 heeft HarryDeKat ***@***.***> het volgende geschreven:﻿
Whoops, dat ben ik inderdaad vergeten, maar als het goed is werken punten op het moment wel. Het opslaan werkt alleen als je op enter klikt, maar ik kan mij voorstellen dat dit wat onduidelijk is, dus mocht ik binnenkort tijd hebben zal ik het aanpassen.

**Comment by HarryDeKat** [comment]
Als het goed is, is de update met de oplossing vandaag beschikbaar. Mochten er nog verdere problemen zijn, hoor ik het graag.
