### ISSUE TITLE
Bug - toevoegen tweede account gaat niet

### ISSUE THREAD

**Issue by wolfjes** [HarryDeKat/Silvio#8]
**Beschrijf de fout*
Ik probeer een tweede account toe te voegen naast mijn eerste kind. Ik krijg een 403 error code
**Fout reproduceren**
Stappen om het gedrag te reproduceren:
1. Ga naar account toevoegen login op magister en foutcode 

**Verwacht gedrag**
Een duidelijke beschrijving van wat u verwachtte dat er zou gebeuren.

**Smartphone (gelieve de volgende gegevens in te vullen):**
  - Toestel: iPhone 11

**Comment by HarryDeKat** [comment]
Hallo @wolfjes, 

Allereerst dank u wel voor het melden van de fout, niet iedereen neemt hier de moeite voor. De oorzaak van de fout is voor mij wat lastig te achterhalen, omdat ik niet precies weet waar de fout vandaan komt. Magister houd hun API-documentatie geheim, dus het is soms lastig om in te schatten welke waardes kunnen verschillen per school. Ik heb wel een poging gedaan om een goede inschatting te maken over de afkomst en ik denk de fout gevonden te hebben. Magister heeft namelijk verschillende account types om studenten, ouders, leraren, etc. uit elkaar te houden, deze hebben allemaal een speciale naam. Ik ging ervanuit dat die namen identiek waren voor elke school, dus gebruikte Silvio die om te controleren welk type account op het moment werd ingelogd, maar waarschijnlijk verschillen deze. Nu wordt er gekeken naar specifieke permissies, waardoor het goede type account wel correct voor alle scholen gedetecteerd wordt. 

De update zal hoogstwaarschijnlijk met een aantal dagen beschikbaar zijn. Mocht de fout terugkeren kan u dit uiteraard aangeven.

Met vriendelijke groeten,
HarryDeKat

**Comment by wolfjes** [comment]
Dankjewel voor het uitzoeken! Supper goed!

**Comment by wolfjes** [comment]
Het lukt nog niet om het tweede account toe te voegen. Het lijkt school specifiek te zijn. Als ik namelijk Silvio verwijder en alleen het "tweede" account toevoeg, dan krijg ik het zelfde. Ik ga de logging er bij doen.
![IMG_3400](https://github.com/HarryDeKat/Silvio/assets/136594427/578392b9-600f-402a-ad3b-6d7c5158f35e)

Ik hoop dat je er wat mee kunt :-)

Als je meer info nodig hebt, hoor ik het graag.

**Comment by wolfjes** [comment]
Yes t werkt . Ik kan nu de twee accounts op 1 Silvio volgen  . Grote dank!

**Comment by HarryDeKat** [comment]
Top, mooi dat het nu werkt. Nogmaals bedankt voor het melden van de fout.
